version: '3.8'  # Docker Compose version

services:
  # Backend Service (Node.js API)
  backend:
    image: cms-backend:latest  # Backend image
    container_name: cms-backend  # Container name
    build:
      context: ./backend  # Build from the backend directory
    ports:
      - "4000:4000"  # Expose backend port
    environment:
      - MONGO_URI=mongodb://mongo:27017/MERN_STACK_HOSPITAL_MANAGEMENT_SYSTEM  # MongoDB URI
    depends_on:
      - mongo  # Wait for MongoDB
    networks:
      - hospital-network  # Connect to network

  # MongoDB Service
  mongo:
    image: mongo:latest  # MongoDB image
    container_name: mongo  # Container name
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - hospital-network  # Connect to network

  # Frontend Service (React UI)
  frontend:
    image: react-user-interface:latest  # Frontend image
    container_name: react-user-interface  # Container name
    build:
      context: ./frontend  # Build from frontend directory
    ports:
      - "5173:5173"  # Expose frontend port
    environment:
      - REACT_APP_API_URL=http://backend:4000  # Set API URL for frontend
    depends_on:
      - backend  # Wait for backend
    networks:
      - hospital-network  # Connect to network

networks:
  hospital-network:
    driver: bridge  # Set the network driver to 'bridge'
