apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: hospital-management-backend
spec:
  selector:
    app: hospital-management-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: hospital-management-frontend
spec:
  selector:
    app: hospital-management-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
